package com.carOwner.entity;

public class TCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_plate_color
     *
     * @mbg.generated
     */
    private String carPlateColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_color
     *
     * @mbg.generated
     */
    private String carColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.id
     *
     * @return the value of t_car.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.id
     *
     * @param id the value for t_car.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.member_id
     *
     * @return the value of t_car.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.member_id
     *
     * @param memberId the value for t_car.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_plate
     *
     * @return the value of t_car.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_plate
     *
     * @param carPlate the value for t_car.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_plate_color
     *
     * @return the value of t_car.car_plate_color
     *
     * @mbg.generated
     */
    public String getCarPlateColor() {
        return carPlateColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_plate_color
     *
     * @param carPlateColor the value for t_car.car_plate_color
     *
     * @mbg.generated
     */
    public void setCarPlateColor(String carPlateColor) {
        this.carPlateColor = carPlateColor == null ? null : carPlateColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.park_id
     *
     * @return the value of t_car.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.park_id
     *
     * @param parkId the value for t_car.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.create_time
     *
     * @return the value of t_car.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.create_time
     *
     * @param createTime the value for t_car.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.update_time
     *
     * @return the value of t_car.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.update_time
     *
     * @param updateTime the value for t_car.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_color
     *
     * @return the value of t_car.car_color
     *
     * @mbg.generated
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_color
     *
     * @param carColor the value for t_car.car_color
     *
     * @mbg.generated
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }
}