package com.carOwner.entity;

public class TDepositCouponRec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.coupon_limit
     *
     * @mbg.generated
     */
    private Integer couponLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.member_name
     *
     * @mbg.generated
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.car_id
     *
     * @mbg.generated
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.car_plate
     *
     * @mbg.generated
     */
    private String carPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.channel_no
     *
     * @mbg.generated
     */
    private String channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.coupon_type
     *
     * @mbg.generated
     */
    private Integer couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.coupon_value
     *
     * @mbg.generated
     */
    private Double couponValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.valid_time
     *
     * @mbg.generated
     */
    private String validTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deposit_coupon_rec.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.id
     *
     * @return the value of t_deposit_coupon_rec.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.id
     *
     * @param id the value for t_deposit_coupon_rec.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.coupon_limit
     *
     * @return the value of t_deposit_coupon_rec.coupon_limit
     *
     * @mbg.generated
     */
    public Integer getCouponLimit() {
        return couponLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.coupon_limit
     *
     * @param couponLimit the value for t_deposit_coupon_rec.coupon_limit
     *
     * @mbg.generated
     */
    public void setCouponLimit(Integer couponLimit) {
        this.couponLimit = couponLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.member_id
     *
     * @return the value of t_deposit_coupon_rec.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.member_id
     *
     * @param memberId the value for t_deposit_coupon_rec.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.member_name
     *
     * @return the value of t_deposit_coupon_rec.member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.member_name
     *
     * @param memberName the value for t_deposit_coupon_rec.member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.car_id
     *
     * @return the value of t_deposit_coupon_rec.car_id
     *
     * @mbg.generated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.car_id
     *
     * @param carId the value for t_deposit_coupon_rec.car_id
     *
     * @mbg.generated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.car_plate
     *
     * @return the value of t_deposit_coupon_rec.car_plate
     *
     * @mbg.generated
     */
    public String getCarPlate() {
        return carPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.car_plate
     *
     * @param carPlate the value for t_deposit_coupon_rec.car_plate
     *
     * @mbg.generated
     */
    public void setCarPlate(String carPlate) {
        this.carPlate = carPlate == null ? null : carPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.park_id
     *
     * @return the value of t_deposit_coupon_rec.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.park_id
     *
     * @param parkId the value for t_deposit_coupon_rec.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.order_id
     *
     * @return the value of t_deposit_coupon_rec.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.order_id
     *
     * @param orderId the value for t_deposit_coupon_rec.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.channel_no
     *
     * @return the value of t_deposit_coupon_rec.channel_no
     *
     * @mbg.generated
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.channel_no
     *
     * @param channelNo the value for t_deposit_coupon_rec.channel_no
     *
     * @mbg.generated
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo == null ? null : channelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.coupon_type
     *
     * @return the value of t_deposit_coupon_rec.coupon_type
     *
     * @mbg.generated
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.coupon_type
     *
     * @param couponType the value for t_deposit_coupon_rec.coupon_type
     *
     * @mbg.generated
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.coupon_value
     *
     * @return the value of t_deposit_coupon_rec.coupon_value
     *
     * @mbg.generated
     */
    public Double getCouponValue() {
        return couponValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.coupon_value
     *
     * @param couponValue the value for t_deposit_coupon_rec.coupon_value
     *
     * @mbg.generated
     */
    public void setCouponValue(Double couponValue) {
        this.couponValue = couponValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.valid_time
     *
     * @return the value of t_deposit_coupon_rec.valid_time
     *
     * @mbg.generated
     */
    public String getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.valid_time
     *
     * @param validTime the value for t_deposit_coupon_rec.valid_time
     *
     * @mbg.generated
     */
    public void setValidTime(String validTime) {
        this.validTime = validTime == null ? null : validTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.status
     *
     * @return the value of t_deposit_coupon_rec.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.status
     *
     * @param status the value for t_deposit_coupon_rec.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.create_time
     *
     * @return the value of t_deposit_coupon_rec.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.create_time
     *
     * @param createTime the value for t_deposit_coupon_rec.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.update_time
     *
     * @return the value of t_deposit_coupon_rec.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.update_time
     *
     * @param updateTime the value for t_deposit_coupon_rec.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deposit_coupon_rec.remark
     *
     * @return the value of t_deposit_coupon_rec.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deposit_coupon_rec.remark
     *
     * @param remark the value for t_deposit_coupon_rec.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}