package com.carOwner.dao;

import com.carOwner.dao.sqlProvider.TCarSqlProvider;
import com.carOwner.entity.TCar;
import com.carOwner.entity.TCarCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @SelectProvider(type= TCarSqlProvider.class, method="countByExample")
    long countByExample(TCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TCarSqlProvider.class, method="deleteByExample")
    int deleteByExample(TCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_car",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_car (id, member_id, ",
        "car_plate, car_plate_color, ",
        "park_id, create_time, ",
        "update_time, car_color)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{carPlate,jdbcType=VARCHAR}, #{carPlateColor,jdbcType=VARCHAR}, ",
        "#{parkId,jdbcType=INTEGER}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{carColor,jdbcType=VARCHAR})"
    })
    int insert(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @InsertProvider(type=TCarSqlProvider.class, method="insertSelective")
    int insertSelective(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCarSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_plate_color", property="carPlateColor", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_color", property="carColor", jdbcType=JdbcType.VARCHAR)
    })
    List<TCar> selectByExample(TCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, car_plate, car_plate_color, park_id, create_time, update_time, ",
        "car_color",
        "from t_car",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_plate_color", property="carPlateColor", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_color", property="carColor", jdbcType=JdbcType.VARCHAR)
    })
    TCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TCar record, @Param("example") TCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TCar record, @Param("example") TCarCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car
     *
     * @mbg.generated
     */
    @Update({
        "update t_car",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "car_plate_color = #{carPlateColor,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "car_color = #{carColor,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TCar record);
}