package com.carOwner.dao;

import com.carOwner.dao.sqlProvider.TCarStatusSqlProvider;
import com.carOwner.entity.TCarStatus;
import com.carOwner.entity.TCarStatusCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCarStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @SelectProvider(type= TCarStatusSqlProvider.class, method="countByExample")
    long countByExample(TCarStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TCarStatusSqlProvider.class, method="deleteByExample")
    int deleteByExample(TCarStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_car_status",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_car_status (id, member_id, ",
        "member_name, car_id, ",
        "car_plate, park_id, ",
        "order_id, in_time, ",
        "out_time, status, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{memberName,jdbcType=VARCHAR}, #{carId,jdbcType=INTEGER}, ",
        "#{carPlate,jdbcType=VARCHAR}, #{parkId,jdbcType=INTEGER}, ",
        "#{orderId,jdbcType=VARCHAR}, #{inTime,jdbcType=VARCHAR}, ",
        "#{outTime,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=VARCHAR}, #{updateTime,jdbcType=VARCHAR})"
    })
    int insert(TCarStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @InsertProvider(type=TCarStatusSqlProvider.class, method="insertSelective")
    int insertSelective(TCarStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCarStatusSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_name", property="memberName", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TCarStatus> selectByExample(TCarStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, member_name, car_id, car_plate, park_id, order_id, in_time, out_time, ",
        "status, create_time, update_time",
        "from t_car_status",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_name", property="memberName", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    TCarStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarStatusSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TCarStatus record, @Param("example") TCarStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarStatusSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TCarStatus record, @Param("example") TCarStatusCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarStatusSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCarStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_status
     *
     * @mbg.generated
     */
    @Update({
        "update t_car_status",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "member_name = #{memberName,jdbcType=VARCHAR},",
          "car_id = #{carId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "in_time = #{inTime,jdbcType=VARCHAR},",
          "out_time = #{outTime,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TCarStatus record);
}