package com.carOwner.dao;

import com.carOwner.dao.sqlProvider.TDepositCouponRecSqlProvider;
import com.carOwner.entity.TDepositCouponRec;
import com.carOwner.entity.TDepositCouponRecCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TDepositCouponRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @SelectProvider(type= TDepositCouponRecSqlProvider.class, method="countByExample")
    long countByExample(TDepositCouponRecCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TDepositCouponRecSqlProvider.class, method="deleteByExample")
    int deleteByExample(TDepositCouponRecCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_deposit_coupon_rec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_deposit_coupon_rec (id, coupon_limit, ",
        "member_id, member_name, ",
        "car_id, car_plate, ",
        "park_id, order_id, ",
        "channel_no, coupon_type, ",
        "coupon_value, valid_time, ",
        "status, create_time, ",
        "update_time, remark)",
        "values (#{id,jdbcType=INTEGER}, #{couponLimit,jdbcType=INTEGER}, ",
        "#{memberId,jdbcType=INTEGER}, #{memberName,jdbcType=VARCHAR}, ",
        "#{carId,jdbcType=INTEGER}, #{carPlate,jdbcType=VARCHAR}, ",
        "#{parkId,jdbcType=INTEGER}, #{orderId,jdbcType=VARCHAR}, ",
        "#{channelNo,jdbcType=VARCHAR}, #{couponType,jdbcType=INTEGER}, ",
        "#{couponValue,jdbcType=DOUBLE}, #{validTime,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(TDepositCouponRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @InsertProvider(type=TDepositCouponRecSqlProvider.class, method="insertSelective")
    int insertSelective(TDepositCouponRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @SelectProvider(type=TDepositCouponRecSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_limit", property="couponLimit", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_name", property="memberName", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_no", property="channelNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_type", property="couponType", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_value", property="couponValue", jdbcType=JdbcType.DOUBLE),
        @Result(column="valid_time", property="validTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<TDepositCouponRec> selectByExample(TDepositCouponRecCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, coupon_limit, member_id, member_name, car_id, car_plate, park_id, order_id, ",
        "channel_no, coupon_type, coupon_value, valid_time, status, create_time, update_time, ",
        "remark",
        "from t_deposit_coupon_rec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_limit", property="couponLimit", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_name", property="memberName", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_no", property="channelNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="coupon_type", property="couponType", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_value", property="couponValue", jdbcType=JdbcType.DOUBLE),
        @Result(column="valid_time", property="validTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    TDepositCouponRec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDepositCouponRecSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TDepositCouponRec record, @Param("example") TDepositCouponRecCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDepositCouponRecSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TDepositCouponRec record, @Param("example") TDepositCouponRecCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TDepositCouponRecSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TDepositCouponRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deposit_coupon_rec
     *
     * @mbg.generated
     */
    @Update({
        "update t_deposit_coupon_rec",
        "set coupon_limit = #{couponLimit,jdbcType=INTEGER},",
          "member_id = #{memberId,jdbcType=INTEGER},",
          "member_name = #{memberName,jdbcType=VARCHAR},",
          "car_id = #{carId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "channel_no = #{channelNo,jdbcType=VARCHAR},",
          "coupon_type = #{couponType,jdbcType=INTEGER},",
          "coupon_value = #{couponValue,jdbcType=DOUBLE},",
          "valid_time = #{validTime,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TDepositCouponRec record);
}