package com.carOwner.dao;

import com.carOwner.dao.sqlProvider.TWechatUserSqlProvider;
import com.carOwner.entity.TWechatUser;
import com.carOwner.entity.TWechatUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TWechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @SelectProvider(type= TWechatUserSqlProvider.class, method="countByExample")
    long countByExample(TWechatUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TWechatUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(TWechatUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_wechat_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_wechat_user (id, member_id, ",
        "open_id, car_id, car_plate, ",
        "vir_car_plate, park_id, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=INTEGER}, #{memberId,jdbcType=INTEGER}, ",
        "#{openId,jdbcType=VARCHAR}, #{carId,jdbcType=INTEGER}, #{carPlate,jdbcType=VARCHAR}, ",
        "#{virCarPlate,jdbcType=VARCHAR}, #{parkId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=VARCHAR}, #{updateTime,jdbcType=VARCHAR})"
    })
    int insert(TWechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=TWechatUserSqlProvider.class, method="insertSelective")
    int insertSelective(TWechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=TWechatUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="vir_car_plate", property="virCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TWechatUser> selectByExample(TWechatUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, member_id, open_id, car_id, car_plate, vir_car_plate, park_id, create_time, ",
        "update_time",
        "from t_wechat_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.INTEGER),
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_id", property="carId", jdbcType=JdbcType.INTEGER),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="vir_car_plate", property="virCarPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR)
    })
    TWechatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TWechatUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TWechatUser record, @Param("example") TWechatUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TWechatUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TWechatUser record, @Param("example") TWechatUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TWechatUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TWechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_user
     *
     * @mbg.generated
     */
    @Update({
        "update t_wechat_user",
        "set member_id = #{memberId,jdbcType=INTEGER},",
          "open_id = #{openId,jdbcType=VARCHAR},",
          "car_id = #{carId,jdbcType=INTEGER},",
          "car_plate = #{carPlate,jdbcType=VARCHAR},",
          "vir_car_plate = #{virCarPlate,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TWechatUser record);
}